### PR TITLE
Added ordering to the roster page

### PR DESCRIPTION
**Pull request by ch222kv**
Added so that you can order the roster based on name, blog posts or pull requests.

### CODE REVIEW

**Comment by krawaller** [comment]
Aww, brilliant, I've been sorely missing having a sort function on the roster page! Thank you Christoffer! :dancer: 

One thing - I'm not too fond of the `orderings` object. That is in fact component `state`, so we should treat it as such and not hide it in the closure! Could you have a go at refactoring that? I think you'll find that code complexity will go down too!

**Comment by ch222kv** [comment]
I can understand that. I had an even worse solution, but I will give it a got at adding it to the state. :)

**Comment by ch222kv** [comment]
There we go!(?) Is that a better solution, or were you thinking of some other, even better solution? :)
Also added my pull request to my .json file.

**Comment by krawaller** [comment]
This looks much better, well done! Now all our state is treated as actual state.

There is, however, one thing you're doing that's not optimal; in the `getXXindex` functions you are manipulating state directly without using `setState`! This is very much verboten.

Also, if I'm not mistaken, in the current solution the sort order will always change when I select a category, even if that category wasn't already selected. That's not very intuitive; normally the sort order should only be flipped when I click the category that was already selected.

My suggestion; deal with the indexes directly in the `setOrderBy` callback. That's the natural place for it - the user just clicked something, and we need to update our state accordingly. There's nothing saying we can only do 1 state update at a time!

**Comment by ch222kv** [comment]
Ah, of course. Good points.
Now I have changed it so that the ordering stays the same unless you click the category twice. Also removed the code that directly changed state.

**Comment by krawaller** [comment]
Much better! Now we're getting closer! Here's your next challenge in the gauntlet (...cause you didn't think you were done, right? :skull: );
-    The `getXXIndex` functions are now pretty useless. Get rid of them, access `this.state.<index>` directly everywhere like you do in render.
-    Right now we have two names per category - `name` + `ni`, `blogposts` + `bi` and `prs` + `pi`. If you only use one single name, we'll be able to optimise the code in a cool way! So as a first step, replace `ni`, `bi` and `pi` with `name`, `blogposts` and `prs`. This means the state object will now look something like this:

```
{
    orderBy: "blogposts",
    name: 1,
    blogposts: -1,
    prs: 1
}
```

And if you already see where I'm going with this, go ahead and try your hand at streamlining the code! :)

**Comment by ch222kv** [comment]
I think that I changed what you were talking about, at least hopefully. :+1:

**Comment by krawaller** [comment]
Indeed you have! Well done! Now we have the power to make both `getOrderedMembers` and `render` much smaller and sexier.

Let's start with the former, `getOrderedMembers`; right now it is a big switch statement:

``` javascript
getOrderedMembers(){
    var index = this.state[this.state.orderBy];
    switch (this.state.orderBy) {
        case "name":
            var order = _.sortBy(members, "name");
            if (index < 0) {
                order.reverse();
            }
            return order;
        case "blogposts":
            return _.sortBy(members, (n)=> {
                return index * n.blogposts.length;
            });
        case "prs":
            return _.sortBy(members, (n)=> {
                return index * n.pullrequests.length;
            });
        default:
            return members;
    }
}
```

But, each case does pretty much the exact same thing - it applies a filter and an index which both depend on `this.state.orderBy`. That tells me that this could could likely be done much easier! Try this:
-    make the filter functions not use the index, since we can't easily make a filter function for `name` which uses the index. Instead we'll reverse afterwards if we need to.
-    make an object variable `filters` where the keys are the 3 orderBy possibilities and the values are the filter functions.
-    now create the list using _.sortBy(members, filters[this.state.orderBy]))
-    ...and reverse the list if the index is -1.

This should make for a very sleek and pretty function!

**Comment by ch222kv** [comment]
And there we go at the next changes. I went ahead and tried to make the render function a little nicer as well, but I assume you got some more pointers at to what to change in it still? :ear:

**Comment by krawaller** [comment]
How on earth did you know?!

But we're getting ever so close now! Here are a few small things I noticed;
-    For the `filters` definition in `getOrderedMembers` - since you're using arrow syntax anyway, you might as well utilise its full power and use implicit return of single statement. Check out `greet5` in [this snippet](https://jsbin.com/cimoke/edit?js,console).
-    The `getTHRow` method used in `render` has a bit of a weird signature - why send in the full `headerTargets` object? Either have that object defined inside `getTHRow`, or just pass `headerTargets[orderBy]`.
-    Be consistent with how you define methods. You should use concise method definition (see [greet3](https://jsbin.com/cimoke/edit?js,console)) for `render` on line 46, and an arrow function for the map callback on line 48.
-    There's not much won by defining the variables `nameRow`, `blogpostRow` and `prRow`. We might as well do the function calls right where they are needed.

The last two bullets touches on a bigger point; the component code is still somewhat hard to read, and part of that has to do with that you're a bit inconsistent in your coding style. Consider this: in `render` you use an anonymous function to map over `members`, ending up with all members in a big `rows` variable. But for the headers we use a helper method defined on the component outside `render`, and we only do 1 row at a time. Granted, the three column headers have somewhat different needs, but this still makes for a very disparate code reading experience. 

Here's my suggestion, which I've been slowly nudging you towards this whole time: Inside `render`, see if you can skip `getTHRow` and instead render all headers into a `headers` variable by looping over the three keys! Something like this:

```
var headers = ["name","blogposts","prs"].map((type)=> <th
  className="cursor-click"
  ...
th>{headerTargets[type]}</th> );
```

**Comment by ch222kv** [comment]
Another step down the long and winding road. :skull:

**Comment by krawaller** [comment]
This is starting to look REALLY sleek, well done, Christoffer! Now we're getting really close, for real!

I noticed one thing, which is totally my fault. Instead of doing this...

```
var headers = ["name", "blogposts", "prs"].map((type, index) => <th
  className="cursor-click"
  style={{width: "25%"}}
  onClick={this.setOrderBy.bind(null, type)}
  key={index}
>{headerTargets[type]}</th>);
```

...we can map directly over the `headerTargets` object! Again, my bad, sorry.

```
var headers = _.map(headerTargets,(headline, type) => <th
  className="cursor-click"
  style={{width: "25%"}}
  onClick={this.setOrderBy.bind(null, type)}
  key={type}
>{headline}</th>);
```

Now for the **FINAL BOSS**, who has been lurking in the shadows all this journey. Now that we've tried to make the code more flexible, let's put that to the test by _adding a new column showing the snippets count_! Hopefully you'll find that your new super-sleek code allows for this change with a minimum of fuzz!

**Comment by ch222kv** [comment]
Correct me if I\m wrong, but if we map over the object headerTargets, [we are not guaranteed to have the "correct" order](http://stackoverflow.com/a/5525820), as in the order we have now. So then the ordering of the headers would be dependent on the JavaScript runtime.

So, I'm not sure if I agree with mapping over `headerTargets`. I could sort it, but that would just add complexity to the code.

**Comment by krawaller** [comment]
Well, that's still technically true, even though you'll be hard pressed to find an execution environment that doesn't respect definition order. But fair enough! 

Christoffer, welcome out on the other side! Well done! :D

**Comment by ch222kv** [comment]
Haha, thank you!

**Comment by Swoot1** [comment]
Nice job! :D

**Pull request merged**
