### PR TITLE
added my stuff

### PR DESCRIPTION
**Pull request by ludwigj**

### CODE REVIEW

**Comment by krawaller** [comment]
Welcome Ludwig! Seems, since you're fashionably late, that you've got yourself a merge conflict. Do you know how to untie that?

**Comment by ludwigj** [comment]
Hi David ,

Yes, i know sadly that Im very late, I started setting my environment and
stuff up last sunday and made my blog post and the JSON at monday and was
thinking of getting my hello world app and running today, and when i
checked the guild i noticed that i had forgot to make a request...
No I am a little rusty, can you help ?

2015-11-18 13:08 GMT+01:00 Krawaller notifications@github.com:

**Comment by krawaller** [comment]
Here's what you need to do in your terminal locally:
-    First we add the original guild repo as a remote: `git remote add upstream https://github.com/krawaller/riaguild2015.git`
-    Now we pull in the new changes that have happened since after you made your fork: `git pull upstream gh-pages`
-    Git will now warn you that there were merge conflicts in `members.js`. Open that file up in your editor - git has now injected the upstream changes next to yours. Select what to keep and save the file
-    Commit the changes and push to your fork. That will update this PR.

Also I should probably look sternly at you and say that well, at this point in the course you're supposed to have invested 20 hours reading up on the environment including Git+Github, so you'd better make time to catch up! But I would say it in a kind voice so that you aren't too scared. :)

**Comment by ludwigj** [comment]
I havent really worked with forks before so thats probably what messed my
mind up, ill look into it some more before doing my next blog file later
tonight,

You have every right to look at me sternly since im not a very good student
and is behind with another course in web-programming, a PHP course which
have deadlines for its re-examination next week so Im trying to do a lot at
the same time. Do you want to have a skype-meeting with me as well or is
that not obligatory?

2015-11-18 13:25 GMT+01:00 Krawaller notifications@github.com:

**Comment by krawaller** [comment]
...aaaaand, you need to read up on the course web. Skype meeting is definitely mandatory. :) 

Time is tight today, but I'm available all day tomorrow!

**Comment by ludwigj** [comment]
Thats what I thought, just wanted it confirmed :)

Is around after lunch alright ?

2015-11-18 14:26 GMT+01:00 Krawaller notifications@github.com:

**Comment by krawaller** [comment]
Sure!

**Pull request closed without merging**
