### PR TITLE
pajn: Add two PRs

### PR DESCRIPTION
**Pull request by Pajn**

### CODE REVIEW

**Comment by krawaller** [comment]
This is all making me really curious about what mr @drager is actually up to! Hasn't he got the latest version at gh-pages, or am I too thick to figure out how it works?

**Comment by drager** [comment]
@krawaller: You need to go to /stream or /dashboard.

**Comment by krawaller** [comment]
Aah, thanx! `stream` gives me some TS throwup, but `dashboard` drew me pretty graphs! So, what's the elevator pitch here? :)

**Comment by drager** [comment]
It will become a tool for monitoring client-side applications. Mostly exception reporting. Currently some hard-coded data though. :)

**Comment by krawaller** [comment]
Huh, interesting! Looking forward to see where this goes!

**Comment by Pajn** [comment]
Now when the deploy is done the line graph is much more pretty :)

**Pull request merged**
