### PR TITLE
adds myself and ninjas

### PR DESCRIPTION
**Pull request by fyrkant**
Ninjas for all!! But the sumo is already taken!

### CODE REVIEW

**Comment by krawaller** [comment]
A beautiful solution, mattias-san! There seems to be a merge conflict thought, likely stemming from ppl having joined after you created your fork. Can you pull the repo again to your fork and see if you can fix? Likely you just need to touch up `members.js` and rebuild!

**Comment by fyrkant** [comment]
Waller-sensei! I think it should be OK now. Yoroshiku onegaishimasu.

**Comment by krawaller** [comment]
Don't forget to open a new PR to add the 2nd blogpost, as well as a link to this PR! Here's the format I had in mind for the latter:

```
"pullrequests": [
    {
        "when": "2015-11-02 14:00",
        "url": "https://github.com/krawaller/riaguild2015/pull/13",
        "description": "Added ninja delight! <3"
    }
]
```

**Comment by fyrkant** [comment]
2nd blogpost? You mean the one I should be writing now?

**Comment by krawaller** [comment]
Ah, sorry, no, I thought the first was the first, but I see now that the second is the first! If you catch my drift.. :)

But do add that PR!

**Comment by fyrkant** [comment]
Haha, yeah I understand, crystal clear! :dancer:

**Pull request merged**
