### PR TITLE
Added blog entry 5

### PR DESCRIPTION
**Pull request by as223jx**

### CODE REVIEW

**Comment by krawaller** [comment]
You really should have more clickbait-friendly titles for your blogposts. Instead of "entry05", how about "eyeballing Redux" or "slapping Redux in the face" or... you get the idea. :)

**Comment by as223jx** [comment]
Or like, "Woman attempts Redux - you'll never guess what happened next!"
Gotcha!
Den 26 nov 2015 08:37 skrev "Krawaller" notifications@github.com:

**Comment by krawaller** [comment]
ROFL! I have nothing further to teach you, you have very evidently reached full enlightenment!

**Comment by krawaller** [comment]
Also, hey - how did you manage to get away with not having had a Skype session with me yet? Please try to catch me for a session as soon as possible!

**Comment by as223jx** [comment]
Oh, okay, I'll make sure to do that!
Den 2 dec 2015 11:09 skrev "Krawaller" notifications@github.com:

**Pull request merged**
