### PR TITLE
Added code example of two-way data binding in blog post.

### PR DESCRIPTION
**Pull request by Swoot1**

### CODE REVIEW

**Comment by krawaller** [comment]
Did you really mean to remove the link to PR 104?

**Comment by krawaller** [comment]
...also, now you might get a merge conflict because I kind of took a liberty - I added a 3rd category, snippets, to the [guild actions page](http://blog.krawaller.se/riaguild2015/#/actions). Since I want to talk a bit about React snippets specifically in the next vlog I needed a good example to show off, so I stole your 2-way data binding example and [JSbin:ified it](https://jsbin.com/soyobe/edit?html,js,output)! But I didn't want to claim credit so I added it as a snippet to your json file. Sorry to hang you out to dry!

**Comment by Swoot1** [comment]
God no :O I've added it back now.

Thanks for giving me credit :)

**Comment by krawaller** [comment]
:+1:

**Pull request merged**
