### PR TITLE
Changed the menu to the react bootstrap menu.

### PR DESCRIPTION
**Pull request by Swoot1**

### CODE REVIEW

**Comment by krawaller** [comment]
...and a great saturday to you too! :D

**Comment by Swoot1** [comment]
And to you :D :rabbit:

**Comment by krawaller** [comment]
Style points for adding the PR in the actual PR :)

**Comment by MoombaDS** [comment]
Just out of curiosity, is there any reason not to use react-router-bootstrap for the navigation elements which would eliminate the need for all the "isActive" checking and the like just by wrapping the NavItems in LinkContainers or IndexLinkContainers? This seems to handle flagging the correct NavItems as active without any extra elaborate code and seems cleaner from my perspective. Of course, I'm just a novice so I could be mistaken in this!

**Comment by Swoot1** [comment]
Not that I can think of. Go for it!

**Pull request merged**
