### PR TITLE
blogupdate

### PR DESCRIPTION
**Pull request by em222iv**
In my latest blogpost I compare meteor and react

### CODE REVIEW

**Comment by krawaller** [comment]
Any particular reason you're not linking directly to the blogpost in your json-file? :D

**Comment by em222iv** [comment]
Ehm, just started out that way and kept with it. I'll add the specific blog post links and make a new pull request if you like :)

**Comment by krawaller** [comment]
just commit the specific links and push to this fork, and the PR will
update!

2016-01-04 13:52 GMT+01:00 em222iv notifications@github.com:

**Comment by krawaller** [comment]
Also, very high time for a chat, methinx! If you can, try to catch me tomorrow!

**Comment by em222iv** [comment]
fixed the blogpost links.

**Comment by krawaller** [comment]
:+1:

**Pull request merged**
