### PR TITLE
Added link to project repo and second blog post

### PR DESCRIPTION
**Pull request by Janste**

### CODE REVIEW

**Comment by krawaller** [comment]
The `projectrepo` prop should just be the name of the project! That way I can generate links both to the code and to the deployed app.

**Comment by Janste** [comment]
Ok. I changed it back to normal text.

**Comment by krawaller** [comment]
Sorry, I was unclear, I mean it should be the name of the **repo**, and not the full url. So in your case the repo is `Janste.github.io`! 

...which means your project won't be accessed through the usual `http://<username>.github.io/<reponame>` but instead `http://<reponame>`, so I'll have to update our links to act accordingly. You're the only one (I think) using the "magical" `<username>.github.io` repo! :)

**Comment by Janste** [comment]
I hope now is everything ok :)

**Comment by krawaller** [comment]
Indees it is!

**Pull request merged**
