### PR TITLE
Added Projects page

### PR DESCRIPTION
**Pull request by MoombaDS**
Added Projects page. (edited this line in)
Changed project description

### CODE REVIEW

**Comment by MoombaDS** [comment]
It's actually been bugging me for a while that it's hard to access people's project repos easily - I like to browse the guild every now and then and check to see what people's projects are looking like and if I can come up with any PRs to make. However, it's kind of a pain to go through the roster and click on each individual, some of whom may not even have a project listed yet or have dead project links.

Therefore, I present the Projects page!

The only thing I'm not 100% convinced on is whether it should be its own page - it could potentially just be that the project repos and descriptions are added to the Roster itself. However, I felt like this cluttered things a little bit and maybe it's better to keep it nice and clean looking? Plus you did mention that the Roster may someday be changed so that it's no longer a table! That's why I chose to go with this route!

What do you think?

**Comment by MoombaDS** [comment]
This is somewhat unrelated and perhaps a bit out of scope, but I imagine it would be cool if members could add tags to their project resulting in a neat tag cloud which could be used to filter projects. This might be a bit overkill when there are so few projects/members though...

**Comment by krawaller** [comment]
Hey, this is cool! I like it! As you said it makes browsing other people's projects much easier, which is something I really want to encourage. Well done!

**Comment by krawaller** [comment]
A thought, which might help to justify not simply doing this in the roster - how about adding a column called "contributors", where you display the badges of everyone who has made a pull request against that person (it MIGHT not be to the actual project, but never mind)? That way it'll be easier to see who has never received one!

**Comment by krawaller** [comment]
Oooh, and maybe filter out those who have no or bogus (eg, `n/a`) repo name!

**Comment by MoombaDS** [comment]
Aha, that's a really good idea! I'll do that!

The reason I didn't filter out the ones with no repo name or that were titled "n/a" or something similar is that it seems like some people actually do have a project (or something related) up despite forgetting to update the name (or whatever reason the name remains that way). Do you think I should filter them from the list entirely, or add a filter which toggles their visibility on and off?

**Comment by krawaller** [comment]
Nah, you're right, never mind the filtering. Too hard to tell what's what. I'll encourage people to update their descs in the next vlog instead.

**Pull request merged**
