### PR TITLE
Added blog post.

### PR DESCRIPTION
**Pull request by Swoot1**

### CODE REVIEW

**Comment by Swoot1** [comment]
As you can see me adding the PR in the same PR as the code is very coincidental. I'm guessing it's because I'm using the same branch all the time. Could you confirm that?

If you find the time I would like to get a hint on how to get the 'gallery' part of the url so that I don't need to hard code it on my redirect. 

And also, if you know a less messy way of setting the radio buttons to checked that would be great too.

**Comment by krawaller** [comment]
Here's my thinking - we're receiving the filter type from the URL via React Router as props (`iconFilter: this.props.params.filter`). There's no need to set that as state. This _isn't_ state, it is a prop! So you can check against `this.props.params.filter` directly. Otherwise it looks pretty good!

If you want real ninja points you could also try to render the three radio buttons in a loop! :)

**Comment by Swoot1** [comment]
Oups, my bad. I can't defend setting it as a state prop.

**Comment by krawaller** [comment]
Better, but taking my evil dictator role seriously I'm still not completely happy!
-    The object you return from `getInitialState` is not state, it's just some constants you use to help with rendering. Trivial perhaps but realising what's state and what's not is at the heart of the poodle, hence my rough stance!
-    Making `getIconBoxesHTML` take a filter function as parameter seems needlessly complicated. The only thing `getIconBoxesHTML` needs to know is what filter is currently in play, and we know that from `this.props.params.filter`. So why not simply have a `switch` statement inside `getIconBoxesHTML` matching that against our 3 known cases?

**Comment by Swoot1** [comment]
You're too fast :) You comment faster than I code. 

I think you'll find the code more pleasing. I still haven't put the logic for fetching the filter in the getIconBoxesHTML but it's no longer a param.

One known issue is that the active menu item is no longer working for the gallery. I will deal with it later I'm gonna carpa dagen lite now.

**Comment by krawaller** [comment]
It is more pleasing, but - `getIconBoxes` might not take a filterFunction as an argument, but it's still a "secret" argument since it fetches it through the cheating `this.getFilterFunction()` call. :)

What would you say about something like this?

```
getIconBoxesHTML: function(){
    var filterFunc = {
        available: (icon) => { return usedicons.hasOwnProperty(icon) === false;},
        taken: (icon) => { return usedicons.hasOwnProperty(icon);}
    }[this.props.params.filter] || () => true;
    return icons.filter(filterFunc).map(function(icon,n){
        return (
           <span key={n} className={usedicons[icon]?"icon chosen":"icon"}>
               {
                   usedicons[icon] ?
                   <Badge id={usedicons[icon]} /> :
                   <Icon icon={icon} />
               }
           </span>
        ); 
    });
}
```

And, hey, what could POSSIBLY be more carping than doing JS code? :wink:

**Comment by Swoot1** [comment]
I think that's one lengthy function but I've updated the function now.

**Comment by krawaller** [comment]
Wha- ...lengthy?! Come on, `getIconBoxesHTML` is sleek like hell now! Way shorter than before, no dependencies apart from component props, a clear responsibility, and only two statements! The last of which is a `.map` call with an inline iterator function, sure, but that function too is short and sweet. And this praise of course has NOTHING to do with the fact that I wrote it... :)

Two things that are still nagging me:
-    You still have the filter constants in `state`. That isn't state.
-    When we need to render things in a loop there are two common approaches to break things up: 
  -    prerender the loop in a variable: `return <div>{prerenderedStuff}</div>;`
  -    render the loop in a separate function: `return <div>{renderStuff()}</div>`;
  
  Both of these methods are fine, but the problem here is that you are using both! Go with one or the other, that'll make things more clear. Here I'd suggest extract the `radioButtons` stuff to a method `getRenderButtonsHTML`.

**Comment by Swoot1** [comment]
Done and done. Sorry about the filter functions in the state I must be blind because I completely missed them. Twice.

**Comment by krawaller** [comment]
One final thing that might be slightly confusing to some; we now have some constants in the module scope (`usedicons`, `FILTER_ALL`, etc) and some on the component (`filters`). I think `filters` should be a module scope variable along with the others.

Using context variables on a React component (`this.something`) is rarely a good idea:
-    If `something` never changes it should be a module scope constant
-    If `something` does change then it should be `state`.

**Comment by krawaller** [comment]
And some cosmetic stuff in `getRenderButtonsHTML`:
-    Instead of storing `self` for use inside the loop you can supply a context parameter to `.map`.
-    If a tag line is very long, a good way to make it more readable is to put every prop on an indented line.

Something like this:

```
getRenderButtonsHTML: function(){
    return this.filters.map(function(filter, i){
        return (<label key={i}>
            {filter.labelText}
            <input
                type="radio"
                name="icon-filter"
                checked={self.props.params.filter === filter.filterName}
                onChange={self.redirectToFilter.bind(self, filter.filterName)}
            />
        </label>);
    },this);
},
```

**Comment by krawaller** [comment]
(Note how I supply `this` as a second parameter to `.map`, on the second to last line above)

**Comment by krawaller** [comment]
And you can remove the residue `var self = this;` from `render`!

**Comment by krawaller** [comment]
Yeah, setting the `map` scope is pretty cool, right? Don't you feel really clever doing it? :D

**Comment by Swoot1** [comment]
Yes, yes! It was very clever of you David :D I'm proud of you. ;)

**Comment by Swoot1** [comment]
Now please merge! :D

**Comment by krawaller** [comment]
Bah, I'm trying to make YOU feel more like a jedi, not scratch my own (admittedly rather big) ego! :)

Please misunderstand me correctly with all this nitpicking - this component was more than ok a gazillion commits ago. I'm keeping on pushing you just because you DO know JavaScript and therefore are ready to take it to the next level!

I do have one last (...) complaint: the `filter` constant is only used in one single place, namely inside `getRenderButtonsHTML`. Therefore I would declare it inside that function, to make the code more clear. One might argue that for performance's sake it is better to declare the filter array in the module scope, but that would only matter if this function is called a gazillion times in a loop, which is not the case here.

**Comment by Swoot1** [comment]
Yes I know your not doing it to be mean.. only but so that I can learn as well. 

It makes me question my code a lot. Scary and good!

**Comment by Swoot1** [comment]
"Is all my code just a lie?" // my brain

**Comment by krawaller** [comment]
Sorry, I'm confusing you - I meant to write "the `filters` constant", not "the `filter` constants". So the variable called `filters` currently in the module scope should be moved to the only function where it is used.

In the current version you have undeclared constants `FILTER_ALL` etc. :)

Here's the issue - we DO use the constants in two places - both in `getIconBoxesHTML` and `getRenderButtonsHTML`. So having the constants in module scope is fine. But the `filters` variable, now that is only used inside `getRenderButtonsHTML`.

So here's my suggestion: put the constants back:

```
    FILTER_ALL: "all",
    FILTER_TAKEN: "taken",
    FILTER_AVAILABLE: "available"
```

In the `filterFunction` part of `getIconBoxesHTML`, use the constants:

```
var filterFunction = {
    [FILTER_AVAILABLE]: (icon) => { return usedicons.hasOwnProperty(icon) === false;},
    [FILTER_TAKEN]: (icon) => { return usedicons.hasOwnProperty(icon);}
}[this.props.params.filter] || (() => true);
```

And finally, in `getRenderButtonsHTML`, also use the constants as you declare `filters` inside that function. And we can simplify to use an object where the keys are the filters and the values are the labels, instead of an array with objects:

```
getRenderButtonsHTML: function(){
    var labels = {
        [FILTER_ALL]:"Show all",
        [FILTER_AVAILABLE]:"Show available",
        [FILTER_TAKEN]:"Show taken"
    };
    return _.map(labels,function(labeltext, filtername){
        return (
            <label key={filtername}>
                {labeltext}
                <input 
                    type="radio" 
                    name="icon-filter" 
                    checked={this.props.params.filter === filtername} 
                    onChange={this.redirectToFilter.bind(this, filtername)}/>
            </label>);
    }, this);
},
```

**Comment by krawaller** [comment]
A semi-religious side note: doing `var self=this;` is _never_ necessary. Either our anonymous function is an iterator for `map` or `reduce` in which case we can supply `this` as the context argument:

```
myArray.map(function(item){ ... },this);
_.map(myArray,function(item){ ... },this);
_.reduce(myArray,function(mem,item){ ... },initialmem,this);
```

...or, if our anonymous function is used in some other way, we can use bind:

```
setTimeout(function(){ ...}.bind(this),3000);
```

**Comment by Swoot1** [comment]
Now that's nice! :D A gold star for you! The solution before was bad.

**Comment by Swoot1** [comment]
Somehow I never have to change context in Angular so I really never use .bind or context sending with map/reduce on a regular day :S And never use self either then that is.

**Comment by krawaller** [comment]
No, I wouldn't say bad. It was ok. What we did now was to take every single opportunity to make the code easier to read, by making sure to call everything by its proper name and putting things in their correct places. Which DOES make the code easier to read and to work with!

All this hardship that I now put you though is at the very heart of this course. What I want from you is not to become a React expert, but to get a feel for how to organise your stuff! This applies to all levels; it can be the high-level application organisation (which is Redux-land), or it can be low-level component rearranging like now.

So - do you see any more opportunities for improvement, or are you happy with the changes? If so, have you rebuilt and tested?

**Comment by Swoot1** [comment]
Hm, must've missed the rebuild. So lodash can take an object as a parameter. That's nice. I was wondering if it was really worth using when there's so many shiny built in functions in JS. 

I'm gonna have another look.

**Comment by Swoot1** [comment]
Before the merge.

**Comment by Swoot1** [comment]
Well, I still don't like that 'gallery' is hardcoded on line 41. Do you know how I can get it from the URL?

**Comment by krawaller** [comment]
Oh, since we're being perfectionists I just noticed one thing: When defining a single-line arrow function we can do it with implicit return and no brackets, right? So instead of this:

```
var filterFunction = {
    [FILTER_AVAILABLE]: (icon) => { return usedicons.hasOwnProperty(icon) === false;},
    [FILTER_TAKEN]: (icon) => { return usedicons.hasOwnProperty(icon);}
}[this.props.params.filter] || (() => true);
```

...we can do this:

```
var filterFunction = {
    [FILTER_AVAILABLE]: (icon) => usedicons.hasOwnProperty(icon) === false,
    [FILTER_TAKEN]: (icon) => usedicons.hasOwnProperty(icon)
}[this.props.params.filter] || (() => true);
```

Note that we we're already using that syntax for the identity filter which returns everything, since `() => true` is the same as `() => { return true; }`!

**Comment by krawaller** [comment]
Regarding using underscore/lodash; yeah, there are fewer reasons to do so now with the new JS goodies, but iterating over objects is hugely useful and the most common reason for me to include it.

**Comment by krawaller** [comment]
Regarding the hardcoded URL: this is a bit of a bother, I agree. Previous versions of ReactRouter allowed us to name our routes and to redirect to names. So we would define the route as this:

```
<Route name="gallery" path="/galler/:filter" handler={Gallery} />
```

...and then in our components we could do this:

```
this.transitionTo("gallery",{filter:"all"});
```

...but that's all gone now. What we can do now is to define all urls in a separate module which we import both to our components and to the main `routes` file. But that seems like a bit of a hassle too...

**Comment by Swoot1** [comment]
I can't think of any more improvements right now and I won't tear the internet apart just to find how to get hold of the url part. I can do it with the location object if you'd like. Otherwise I'll let it be.

**Comment by krawaller** [comment]
Well done, ms Swoot1! :D

**Comment by Swoot1** [comment]
you too :+1:

**Pull request merged**
