### PR TITLE
Added info about myself; Oskar Klintrot

### PR DESCRIPTION
**Pull request by OskarKlintrot**

### CODE REVIEW

**Comment by krawaller** [comment]
Please use exact github username as `members.js` key and `.json` filename! In you case, lower case! :)

**Comment by OskarKlintrot** [comment]
Are you sure? If you take a look at https://github.com/OskarKlintrot you see that I actually use upper case for the first letter in my names. If I choose "Change username" my current username is spelled "OskarKlintrot".

**Comment by krawaller** [comment]
In that case you wrote your github user name wrong inside your JSON file, so please change it there instead! :)

**Comment by OskarKlintrot** [comment]
Good start on the course! :) Anyway, I fixed it now so it should be fine to merge.

**Pull request merged**
