### PR TITLE
name on taken icon

### PR DESCRIPTION
**Pull request by fyrkant**
Shows the name on the taken icon! 

But hey Waller-sensei, why do you use a weird id from the index of the alphabetically sorted members-array as a route and not the github-name or something? I wanted to link the taken icon to the takee (real word? I don't care!) but getting the id is a hassle!

### CODE REVIEW

**Comment by krawaller** [comment]
The n-as-a-route-id was a temporary bug! Github name is the url parameter. So I suggest that in the reduce you store `data.id` instead of `data.name`, and then you display `members[usedicon[iconname]].name`

**Comment by fyrkant** [comment]
I've added some linking functionality to the Icon-component now! And added it to the action-list.

**Comment by krawaller** [comment]
Hmm - not sure I'm a fan of the linking. Here's what I would prefer - `icon.js` stays the same as before (ie, just showing a pic). Instead we introduce a new component `badge.js` which takes a username as a prop and displays icon+name, wrapping both in a link

**Comment by fyrkant** [comment]
It's the dependency to members and react-router in the otherwise so simple icon.js that irks you? I also felt a little dirty about it...

**Comment by krawaller** [comment]
No, not that, but that I see the need for a badge-like component showing icon and name. And that component should be one single link, which isn't possible if the icon is a link of its own.

**Comment by krawaller** [comment]
Hmm, which is kind of what you have built, I realise now, except you're adding the name and using that as link, and the icon isn't clickable. So if you make the link surround the name and the icon, you have what I describe! But, I would still prefer to have that as a separate component, I think. Icon should just be used to display an image, encapsulating the url logic.

**Comment by fyrkant** [comment]
Yep yep, working on it sensei! Wax on, wax off.

**Comment by fyrkant** [comment]
Badges!

**Comment by krawaller** [comment]
Mr grumpy still not happy - the link should be inside the badge render! :)

**Comment by fyrkant** [comment]
Ahh, of course! Easy fix. :godmode:

**Comment by fyrkant** [comment]
Something like this?

**Comment by krawaller** [comment]
Aaaaalmost - should use the badge in `roster.js` too!

**Comment by fyrkant** [comment]
I didn't want to do my ASP.net-homework anyway! :kissing_heart:

**Comment by fyrkant** [comment]
:metal: ?

**Comment by krawaller** [comment]
:metal:

**Pull request merged**
