### PR TITLE
New blog post and project link

### PR DESCRIPTION
**Pull request by MoombaDS**

### CODE REVIEW

**Comment by MoombaDS** [comment]
Filtering inspired by this pull request: https://github.com/krawaller/riaguild2015/pull/62

There's a fair chance I did not do this in a very efficient way as my JavaScript/React-Fu is not very advanced!

**Comment by krawaller** [comment]
Hmm, not entirely sure how useful this is - if you want to see an individual's deeds, you can simply click on him/her. But, I kind of like it anyway! :)

Don't forget to add PR to your file afterwards!

**Comment by MoombaDS** [comment]
That's a very good point - I guess I lost sight of that in my eagerness to practice!

**Comment by krawaller** [comment]
Here are some thoughts on how to make it seem more in place:
-    Add the exact same thing to the **What** column, filtering `info.description`
-    Add a "show all / posts / PR:s" selection much like what [Elin](http://blog.krawaller.se/riaguild2015/#/member/swoot1) added for [the gallery](http://blog.krawaller.se/riaguild2015/#/gallery) in [this PR](https://github.com/krawaller/riaguild2015/pull/62)
-    Move all controls so they are below the **Who**/**What**/ headings inside the `<th>` cells

No pressure! :innocent:

**Comment by krawaller** [comment]
Oh, forgot:
-    You could also make it so that it searches for the filter _inside_ the target string (name/description), and not just match it to the beginning. That would make it more useful.
-    There really isn't any need to replace `nameFilterFunction` inside `handleNameFilterChange`. See if you can refactor away that!

**Comment by MoombaDS** [comment]
On further reflection, perhaps the most useful place for a name filter function would actually be the roster itself in the event that the list of members became quite long and you didn't want to scroll to find someone. Does this seem worth doing at the same time?

Otherwise, I'll get right on it!

**Comment by krawaller** [comment]
I'm thinking the Roster could be more improved by displaying the users differently, not in a vertical table but floating boxes or something. So my spontaneous thinking is to find another solution there later, leave it for now and go bananas in the Deeds list instead! :)

**Pull request merged**
