### PR TITLE
Added PR to JSON and refactored code

### PR DESCRIPTION
**Pull request by MoombaDS**
Added PR 65 to JSON file
Refactored code to remove replacement of typeFilterFunction

I changed it to check state inside the typeFilterFunction instead - would this be a better way of doing it?

### CODE REVIEW

**Comment by krawaller** [comment]
I think this looks much better. Now `filterType` is part of state, which it should be, and the code becomes much cleaner. Before, when you replaced `typeFilterFunction`, that in essence became a hidden state, making the component harder to understand.

**Comment by MoombaDS** [comment]
Aha I see! I got the idea to use function replacement from the way the icons are being filtered but I can see now why this was the better way to go about it here.

Does this also count as a PR that needs to be registered? Haha

**Comment by krawaller** [comment]
Oh, right! I must've been sloppy when I read that code. Then I am to blame, since I told you to do like she did! :D

Gonna tell her to check this discussion out and see if she wants to update her code too.

**Comment by MoombaDS** [comment]
Not at all! It was a good learning experience anyway!

By the way, you didn't tell me whether I should register this PR in the guild or not - should I?

**Comment by krawaller** [comment]
Do it :)

**Pull request merged**
