### PR TITLE
correcting misstake, format is changed to be registered in json under…

### PR DESCRIPTION
**Pull request by SheriefBadran**
… deepdive.

### CODE REVIEW

**Comment by krawaller** [comment]
I've sent some mixed messages about that. Apologies! Please also publish a short blog post linking the deepdive!

**Comment by krawaller** [comment]
Also, you need to make your video public :)

**Comment by SheriefBadran** [comment]
consider it done mr Waller :)

**Comment by SheriefBadran** [comment]
video should be public now.

**Comment by SheriefBadran** [comment]
... and a blogpost linking the deepdive.

**Comment by krawaller** [comment]
Cheers mate!

**Pull request merged**
