### PR TITLE
Added myself, blogpost and projectrepo

### PR DESCRIPTION
**Pull request by ch222kv**

### CODE REVIEW

**Comment by krawaller** [comment]
Seems there are some merge conflicts since the files you've edited have been changed after you made your fork. 

Either fork afresh or do the following locally:
-    `git remote add realguild https://github.com/krawaller/riaguild2015.git`
-    `git pull original realguild`
-    Git will now tell you which files have merge conflicts, likely `members.js`. Open that file and fix the conflicts manually (git will now show both your changes and the upstream changes and you have to choose). If `bundle.js` is the merge conflict simply rebuild.
-    `git commit -am "fixed merge conflict"`
-    and finally push to this fork again, which will make this PR update!

**Comment by ch222kv** [comment]
It seems that it was only the bundle.js that had a conflict, so now it should be resolved!

**Comment by krawaller** [comment]
Apologies - that was the case, but I updated the guild again before noticing your update. Sorry!! So, now you have to rebuild and push again. :)

Note that you don't need to rebuild when you submit an update to your .json file - I'll do that locally as I pull in your changes, then push it up to Github.

**Comment by ch222kv** [comment]
Well, then... :)
I have resolved the conflict once again, please don't make me do it again!

**Comment by krawaller** [comment]
:)

**Pull request merged**
