### PR TITLE
- Made the nav bar use react-router-bootstrap to decide whether it's …

### PR DESCRIPTION
**Pull request by MoombaDS**
…active or not

This initially seemed like it might be a good idea but in retrospect I feel like I may have done it either in an inefficient manner or that it was entirely unnecessary in the first place.

### CODE REVIEW

**Comment by krawaller** [comment]
Haha, yeah, I know that feeling! :)

Ok, help me break this stuff down. Originally I made the menu by supplying an `activeClassLink` prop to the React Router `Link` element (see docs [here](https://github.com/rackt/react-router/blob/master/docs/API.md#link)).

Then @Swoot1 wanted to use React Bootstrap instead, which (I believe?) means we want an eventual `active` class to be applied to a surrounding `li` tag instead of directly on the `a` tag, which means we can't use the React Router link as is. @Swoot1 therefore built her own link which parsed the current path to see if the link should be active. What I should have told her to do instead would be to use the `isActive` method supplied by React Router's `History` mixin (documentation [here](https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query-indexonly)).

Now you propose using the `React Router Bootstrap` lib which is a tiny library that pretty much does the suggestion above but under the hood, along with a few other niceties. 

Have I got that right?

**Comment by MoombaDS** [comment]
Looking at the code that was in place before I made my revisions, it looks to me like it actually was using the isActive method from React Router's History mixin.

Otherwise yeah, that seems like pretty much what I had in mind, though I have no idea whether it would really be better!

**Comment by krawaller** [comment]
Here's a wish from your malevolent course dictator - could you write a short post comparing the 3 approaches? Maybe I could even persuade @Swoot1 to do the same thing and if you disagree we can have a brilliant discussion / fight to the death? :D

Either way, I'd like to merge this, but there seems to be a merge conflict! Know how to untangle that?

**Comment by MoombaDS** [comment]
It looks like the issue was just the bundle - I think I rebuilt it correctly now.

I'll do some more research into the other two methods and see what I can come up with!

**Comment by krawaller** [comment]
Brilliant!

**Pull request merged**
